// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcJd6OS1Npj9WNqyDgL3bBmS502ZlBcdY',
    appId: '1:809647291393:web:0ba68012ef67f9fc995400',
    messagingSenderId: '809647291393',
    projectId: 'chatapp-9d3ab',
    authDomain: 'chatapp-9d3ab.firebaseapp.com',
    storageBucket: 'chatapp-9d3ab.appspot.com',
    measurementId: 'G-JN8MQB8YVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASx05UN2_qqjLYWjIYTo9BKIu4sMs2uVc',
    appId: '1:809647291393:android:dd7518562aa30cc2995400',
    messagingSenderId: '809647291393',
    projectId: 'chatapp-9d3ab',
    storageBucket: 'chatapp-9d3ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp4A8TJaVL5gRodzpG35ek6NfcpkAs9PE',
    appId: '1:809647291393:ios:ab19a3aacf1f2fa4995400',
    messagingSenderId: '809647291393',
    projectId: 'chatapp-9d3ab',
    storageBucket: 'chatapp-9d3ab.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp4A8TJaVL5gRodzpG35ek6NfcpkAs9PE',
    appId: '1:809647291393:ios:ba209748606e33ac995400',
    messagingSenderId: '809647291393',
    projectId: 'chatapp-9d3ab',
    storageBucket: 'chatapp-9d3ab.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
